name: Test

on: [workflow_dispatch, workflow_call, push, pull_request]

jobs:
  run-test-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-v1

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: '25'
          cache: gradle

      - name: Make test.sh executable
        run: chmod +x test.sh

      - name: Run test.sh
        run: ./test.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGES_RW_ACTOR: ${{ secrets.PACKAGES_RW_ACTOR }}
          PACKAGES_RW_TOKEN: ${{ secrets.PACKAGES_RW_TOKEN }}
